### ISSUE TITLE
every field appear on registration form

### ISSUE THREAD

**Issue by Ya-Ri** [sbrajesh/conditional-profile-fields-for-buddypress#3]
Hi,
thanks fo this plugin, it works but i found an issue using it:
by default, all the conditionnal fields are show.
For example in the registration form, based on a country, a choice of city will be displayed...but it display all the cities fields related to each country
Do you experience the same issue?
Regards,
YaRi

**Comment by sbrajesh** [comment]
Closing as fixed in prev version and tested.
